name: CI

  on:
    pull-request:
      branches: develop
  job:
    build:
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
              node-version: "12.x"
        - run: npm ci
        - run: nmp test -- --coverage
          env:
            CI: true